# Generated by Django 4.2.30 on 2026-04-14 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Employee assigned to handle this appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributed_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
