# Generated by Django 4.2.30 on 2026-04-14 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0002_appointment_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='guest_age',
            field=models.PositiveIntegerField(blank=True, help_text='Guest patient age', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='guest_email',
            field=models.EmailField(blank=True, help_text='Guest patient email', max_length=254),
        ),
        migrations.AddField(
            model_name='appointment',
            name='guest_full_name',
            field=models.CharField(blank=True, help_text='Guest patient name', max_length=200),
        ),
        migrations.AddField(
            model_name='appointment',
            name='guest_gender',
            field=models.CharField(blank=True, help_text='Guest patient gender', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='guest_phone',
            field=models.CharField(blank=True, help_text='Guest patient phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
