# Generated by Django 6.0.4 on 2026-04-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_hospital_icu_beds_available_hospital_total_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorhospital',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Consultation fee for this hospital', max_digits=10),
        ),
        migrations.AddField(
            model_name='doctorhospital',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Service charge for this hospital', max_digits=10),
        ),
    ]
