# Generated by Django 6.0.4 on 2026-04-14 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorhospital_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='custom_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='custom_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='is_exception',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DoctorWeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='doctors.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_weekly_schedules', to='doctors.hospital')),
            ],
            options={
                'verbose_name': 'Doctor Weekly Schedule',
                'verbose_name_plural': 'Doctor Weekly Schedules',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('doctor', 'hospital', 'day_of_week')},
            },
        ),
    ]
